VAGRANT_BOX = "ubuntu/bionic64"
MEMORY = 1024
CPUS = 1
NETWORK = "192.168.56.110"
HOSTNAME = "lduheronS"

Vagrant.configure("2") do |config|
  config.vm.box = VAGRANT_BOX
  config.vm.boot_timeout = 600
  config.vm.box_check_update = true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = MEMORY
    vb.cpus = CPUS
    vb.linked_clone = true
  end

  config.vm.define HOSTNAME do |node|
    node.vm.hostname = HOSTNAME
    node.vm.network "private_network", ip: NETWORK
  
    node.vm.provider "virtualbox" do |vb|
      vb.name = HOSTNAME    
    end
  end 
end
