VAGRANT_BOX = "ubuntu/bionic64"
MEMORY = 4096
CPUS = 4
NETWORK = "192.168.56.110"
HOSTNAME = "lduheronS"

Vagrant.configure("2") do |config|
  config.vm.box = VAGRANT_BOX
  config.vm.boot_timeout = 600
  config.vm.box_check_update = true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = MEMORY
    vb.cpus = CPUS
    vb.linked_clone = true
  end

  config.vm.define HOSTNAME do |node|
    node.vm.hostname = HOSTNAME
    node.vm.network "private_network", ip: NETWORK
  
    node.vm.provider "virtualbox" do |vb|
      vb.name = HOSTNAME    
    end
    node.vm.provision "shell", path: "scripts/server.sh"
  end
end

# Vagrantfile for setting up a 3-node K3s Kubernetes cluster (1 master, 2 workers)
# Vagrant.configure("2") do |config|
#     # Define a common base configuration for all VMs
#     config.vm.box = "ubuntu/bionic64"
#      config.vm.boot_timeout = 600
  
#     # Define the master node
#     config.vm.define "lduheronS" do |master|
#       master.vm.hostname = "lduheronS"
#       master.vm.network "private_network", ip: "192.168.56.110"
#       master.vm.provider "virtualbox" do |vb|
#         vb.memory = "1024"
#         vb.cpus = 1
#       end
#       master.vm.provision "shell", path: "scripts/server.sh"
#     end
#   end