apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ftegan-app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: http://gitlab.172.17.0.1.nip.io:8080/root/ftegan.git
    targetRevision: HEAD
    path: configs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true