global:
  hosts:
    domain: localhost
    externalIP: 127.0.0.1
    externalUrl: http://localhost:8880

  ingress:
    configureCertmanager: false
    tls:
      enabled: false

certmanager:
  install: false

nginx-ingress:
  enabled: false

gitlab:
  webservice:
    service:
      externalPort: 8880
